{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: {{ include "github-rate-limit-checker.podDisruptionBudget.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "github-rate-limit-checker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "github-rate-limit-checker.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "github-rate-limit-checker.selectorLabels" . | nindent 6 }}
{{- end }}
