{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "github-rate-limit-checker.fullname" . }}
  namespace: {{ .Values.podMonitor.namespace | default .Release.Namespace }}
  labels:
    {{- include "github-rate-limit-checker.labels" . | nindent 4 }}
    {{- with .Values.podMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "github-rate-limit-checker.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
  - port: {{ .Values.metrics.portName }}
    interval: {{ .Values.podMonitor.interval }}
    scrapeTimeout: {{ .Values.podMonitor.scrapeTimeout }}
    path: /metrics
{{- end }}
